"use client";
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "../../components/Card";
import { Button } from "../../components/Button";
import { Badge } from "../../components/Badge";
import { Brain, Sparkles, Zap, Target, Shield, BarChart3 } from "lucide-react";
import EnhancedQuestionnaire from "../components/EnhancedQuestionnaire";
import EnhancedPlanSummary from "../components/EnhancedPlanSummary";
import { buildPlan } from "../domain/allocationEngine";

export default function EnhancedDemo() {
  const [step, setStep] = useState<'intro' | 'questionnaire' | 'results'>('intro');
  const [samplePlan, setSamplePlan] = useState<any>(null);

  // Sample sophisticated plan for demonstration
  const demoAnswers = {
    age: "25-35",
    investmentHorizon: "10-20 years",
    annualIncome: "1L-2L",
    investmentAmount: 500000,
    emergencyFundMonths: "4-6",
    dependents: "0",
    monthlyObligations: "10K-25K",
    volatilityComfort: "stay_calm",
    maxAcceptableLoss: "20%",
    investmentKnowledge: "some_knowledge",
    primaryGoal: "wealth_building",
    expectedReturn: "12-15%",
    liquidityNeeds: "few_times_year",
    jobStability: "somewhat_stable",
    withdrawalNext2Years: false,
    hasInsurance: true,
    avoidAssets: []
  };

  const generateSamplePlan = () => {
    const plan = buildPlan(demoAnswers);
    setSamplePlan(plan);
    setStep('results');
  };

  const handleQuestionnaireComplete = (allocation: any) => {
    setSamplePlan(allocation);
    setStep('results');
  };

  if (step === 'questionnaire') {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 p-6">
        <div className="max-w-6xl mx-auto">
          <div className="mb-6">
            <Button 
              variant="outline" 
              onClick={() => setStep('intro')}
              className="mb-4"
            >
              ← Back to Demo
            </Button>
            <h1 className="text-3xl font-bold text-center mb-2">
              10-Advisor Council Questionnaire
            </h1>
            <p className="text-center text-muted-foreground">
              Experience professional-grade financial risk profiling
            </p>
          </div>
          
          <EnhancedQuestionnaire 
            onComplete={handleQuestionnaireComplete}
            showProgress={true}
            allowSkip={false}
          />
        </div>
      </div>
    );
  }

  if (step === 'results' && samplePlan) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 p-6">
        <div className="max-w-6xl mx-auto">
          <div className="mb-6">
            <Button 
              variant="outline" 
              onClick={() => setStep('intro')}
              className="mb-4"
            >
              ← Back to Demo
            </Button>
            <div className="text-center space-y-2">
              <h1 className="text-3xl font-bold">
                Your Sophisticated Investment Plan
              </h1>
              <p className="text-muted-foreground">
                Generated by our 10-Advisor Council AI
              </p>
              <Badge className="bg-green-500 text-white">
                Professional Grade Analysis
              </Badge>
            </div>
          </div>
          
          <EnhancedPlanSummary 
            plan={samplePlan}
            showDetails={true}
            showStressTest={true}
            showSignalAnalysis={true}
          />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Hero Section */}
        <div className="text-center space-y-6 mb-12">
          <div className="space-y-2">
            <Badge className="bg-blue-500 text-white mb-4">
              🚀 NEW: Enhanced Allocation Engine
            </Badge>
            <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              10-Advisor Council
            </h1>
            <h2 className="text-3xl font-semibold text-gray-800 dark:text-gray-200">
              Professional Investment Allocation
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Experience the world's most sophisticated personal finance allocation engine. 
              Our AI Council delivers professional-grade investment advice with human-like explanations.
            </p>
          </div>

          <div className="flex justify-center gap-4">
            <Button 
              size="lg" 
              onClick={() => setStep('questionnaire')}
              className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
            >
              <Brain className="w-5 h-5 mr-2" />
              Try Enhanced Questionnaire
            </Button>
            <Button 
              size="lg" 
              variant="outline"
              onClick={generateSamplePlan}
            >
              <Sparkles className="w-5 h-5 mr-2" />
              See Sample Results
            </Button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-6 mb-12">
          <Card className="border-2 border-blue-200 hover:border-blue-300 transition-colors">
            <CardHeader className="text-center">
              <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Brain className="w-6 h-6 text-blue-600" />
              </div>
              <CardTitle>Multi-Factorial Analysis</CardTitle>
              <CardDescription>
                29 professional questions across 5 categories with weighted signal processing
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Age & time horizon analysis
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Financial situation assessment
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Risk tolerance profiling
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Goal-aware adjustments
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="border-2 border-green-200 hover:border-green-300 transition-colors">
            <CardHeader className="text-center">
              <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Target className="w-6 h-6 text-green-600" />
              </div>
              <CardTitle>Dynamic Base Allocation</CardTitle>
              <CardDescription>
                No rigid templates - pure signal-based allocation calculation
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Weighted signal processing
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Smart equity/safety split
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Behavioral finance factors
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Asset-specific intelligence
                </li>
              </ul>
            </CardContent>
          </Card>

          <Card className="border-2 border-purple-200 hover:border-purple-300 transition-colors">
            <CardHeader className="text-center">
              <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-3">
                <Shield className="w-6 h-6 text-purple-600" />
              </div>
              <CardTitle>Human-Like Explanations</CardTitle>
              <CardDescription>
                Professional advisor-quality rationale for every decision
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Context-aware explanations
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Stress testing analysis
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Risk scenario modeling
                </li>
                <li className="flex items-center gap-2">
                  <Zap className="w-4 h-4 text-yellow-500" />
                  Signal transparency
                </li>
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* Comparison Section */}
        <Card className="mb-12">
          <CardHeader className="text-center">
            <CardTitle className="text-2xl">Before vs After</CardTitle>
            <CardDescription>
              See the difference between basic and professional-grade allocation
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-8">
              {/* Before */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-red-600">❌ Old Basic Engine</h3>
                <div className="space-y-2 text-sm">
                  <div className="p-3 bg-red-50 rounded border-l-4 border-red-300">
                    <strong>Simple Questions:</strong> 8 basic questions
                  </div>
                  <div className="p-3 bg-red-50 rounded border-l-4 border-red-300">
                    <strong>Fixed Templates:</strong> Rigid 20/40/60 allocations
                  </div>
                  <div className="p-3 bg-red-50 rounded border-l-4 border-red-300">
                    <strong>Basic Rationale:</strong> Generic explanations
                  </div>
                  <div className="p-3 bg-red-50 rounded border-l-4 border-red-300">
                    <strong>No Analysis:</strong> No stress testing or signals
                  </div>
                </div>
              </div>

              {/* After */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-green-600">✅ New 10-Advisor Council</h3>
                <div className="space-y-2 text-sm">
                  <div className="p-3 bg-green-50 rounded border-l-4 border-green-300">
                    <strong>Professional Questions:</strong> 29 weighted questions across 5 categories
                  </div>
                  <div className="p-3 bg-green-50 rounded border-l-4 border-green-300">
                    <strong>Dynamic Allocation:</strong> Signal-based calculation with no templates
                  </div>
                  <div className="p-3 bg-green-50 rounded border-l-4 border-green-300">
                    <strong>Human-Like Advice:</strong> Context-aware professional explanations
                  </div>
                  <div className="p-3 bg-green-50 rounded border-l-4 border-green-300">
                    <strong>Full Analysis:</strong> Stress testing, signals, and risk scoring
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Technical Details */}
        <Card>
          <CardHeader className="text-center">
            <CardTitle className="text-2xl flex items-center justify-center gap-2">
              <BarChart3 className="w-6 h-6" />
              Technical Excellence
            </CardTitle>
            <CardDescription>
              Built with professional-grade financial engineering
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <h3 className="font-semibold mb-3">🧠 Signal Processing Engine</h3>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  <li>• Multi-factorial weighted signals (-15 to +15)</li>
                  <li>• Age factors (25% weight)</li>
                  <li>• Financial situation (30% weight)</li>
                  <li>• Risk tolerance (25% weight)</li>
                  <li>• Goals & objectives (20% weight)</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-3">⚡ Dynamic Calculation</h3>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  <li>• 50% neutral equity baseline</li>
                  <li>• Weighted signal aggregation</li>
                  <li>• Smart asset split intelligence</li>
                  <li>• Goal-aware tactical adjustments</li>
                  <li>• Avoided asset redistribution</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-3">🛡️ Stress Testing</h3>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  <li>• 2008 Financial Crisis scenario</li>
                  <li>• 2020 Pandemic shock analysis</li>
                  <li>• High inflation (1970s-style)</li>
                  <li>• Interest rate spike modeling</li>
                  <li>• Emergency fund adequacy</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-3">💡 Human-Like AI</h3>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  <li>• Context-aware rationale generation</li>
                  <li>• Plain English explanations</li>
                  <li>• Behavioral finance considerations</li>
                  <li>• Professional advisor tone</li>
                  <li>• Transparent signal analysis</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}